"""Merge Request processor with Jira integration.

This module processes Merge Requests and syncs them with Jira:
1. Extract Jira issue key from MR title/description
2. Generate AI summary from commits
3. Post comment to Jira issue
4. Update Jira issue status based on MR state
"""

import logging
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

from app.jira_integration.config import JiraConfig
from app.jira_integration.jira_client import JiraClient, find_transition_id

logger = logging.getLogger(__name__)


class MRState(str, Enum):
    """GitLab MR states for transition mapping."""

    OPENED = "opened"
    APPROVED = "approved"
    MERGED = "merged"
    CLOSED = "closed"


# Mapping from MR state to Jira transition name
MR_TO_JIRA_TRANSITION: dict[MRState, str] = {
    MRState.OPENED: "In Progress",
    MRState.APPROVED: "Review",
    MRState.MERGED: "Done",
}


@dataclass
class MergeRequest:
    """GitLab Merge Request data."""

    iid: int
    project_id: int
    source_branch: str
    target_branch: str
    title: str
    description: Optional[str]
    state: MRState
    web_url: str
    author: dict[str, Any] = field(default_factory=dict)


@dataclass
class Commit:
    """GitLab commit data."""

    id: str
    message: str
    author_name: str
    author_email: str
    timestamp: str


class MRProcessor:
    """
    Process Merge Requests and sync with Jira.

    Workflow:
        Git push → MR created → AI summary → Jira comment → Jira status update
    """

    def __init__(self, config: JiraConfig, jira_client: JiraClient):
        """
        Initialize MR processor.

        Args:
            config: Jira configuration.
            jira_client: Jira API client instance.
        """
        self.config = config
        self.jira = jira_client

    def _generate_ai_summary(
        self,
        mr: MergeRequest,
        commits: list[Commit],
    ) -> str:
        """
        Generate AI summary for the merge request.

        Args:
            mr: Merge request data.
            commits: List of commits in the MR.

        Returns:
            Formatted summary text.
        """
        commit_list = "\n".join(f"- {c.message}" for c in commits[:10])
        if len(commits) > 10:
            commit_list += f"\n- ... and {len(commits) - 10} more commits"

        summary = f"""🤖 AI Summary for MR !{mr.iid}

**Title:** {mr.title}
**Branch:** `{mr.source_branch}` → `{mr.target_branch}`
**Author:** {mr.author.get('name', 'Unknown')}

**Commits ({len(commits)} total):**
{commit_list}

**Description:**
{mr.description or 'No description provided.'}

---
*This summary was automatically generated by AI-Git-Jira integration.*
"""
        return summary

    def _extract_jira_issue_key(self, mr: MergeRequest) -> Optional[str]:
        """
        Extract Jira issue key from MR title or description.

        Looks for patterns like: PROJ-123, [PROJ-123], etc.

        Args:
            mr: Merge request data.

        Returns:
            Jira issue key if found, None otherwise.
        """
        # Pattern for Jira issue key (e.g., PROJ-123)
        pattern = r"\b([A-Z]+-\d+)\b"

        # Search in title first
        match = re.search(pattern, mr.title)
        if match:
            return match.group(1)

        # Search in description
        if mr.description:
            match = re.search(pattern, mr.description)
            if match:
                return match.group(1)

        return None

    def _get_transition_id_for_state(
        self,
        issue_key: str,
        mr_state: MRState,
    ) -> Optional[str]:
        """
        Get Jira transition ID for MR state.

        Args:
            issue_key: Jira issue key.
            mr_state: GitLab MR state.

        Returns:
            Transition ID if found, None otherwise.
        """
        transition_name = MR_TO_JIRA_TRANSITION.get(mr_state)
        if not transition_name:
            logger.warning("No transition mapping for MR state: %s", mr_state)
            return None

        transitions = self.jira.get_transitions(issue_key)
        transition_id = find_transition_id(transitions, transition_name)

        if not transition_id:
            logger.warning(
                "Transition '%s' not found for issue %s. Available: %s",
                transition_name,
                issue_key,
                [t.get("name") for t in transitions],
            )

        return transition_id

    def process_mr(
        self,
        mr: MergeRequest,
        commits: list[Commit],
    ) -> dict[str, Any]:
        """
        Process a Merge Request and sync with Jira.

        Workflow:
            1. Extract Jira issue key from MR
            2. Generate AI summary
            3. Add comment to Jira issue
            4. Update Jira issue status based on MR state

        Args:
            mr: Merge request data.
            commits: List of commits in the MR.

        Returns:
            Processing result with status and details.
        """
        result: dict[str, Any] = {
            "success": False,
            "issue_key": None,
            "comment_added": False,
            "transition_applied": False,
            "errors": [],
        }

        # Extract Jira issue key
        issue_key = self._extract_jira_issue_key(mr)
        if not issue_key:
            logger.info("No Jira issue key found in MR !%d, skipping Jira sync", mr.iid)
            result["errors"].append("No Jira issue key found")
            return result

        result["issue_key"] = issue_key
        logger.info("Processing MR !%d for Jira issue %s", mr.iid, issue_key)

        try:
            # Verify issue exists
            self.jira.get_issue(issue_key)
        except Exception as e:
            logger.error("Jira issue %s not found or inaccessible: %s", issue_key, e)
            result["errors"].append(f"Issue {issue_key} not found: {e}")
            return result

        # Generate and add AI summary as comment
        try:
            summary = self._generate_ai_summary(mr, commits)
            comment_result = self.jira.add_comment(issue_key, summary)
            result["comment_added"] = comment_result is not None
        except Exception as e:
            logger.error("Failed to add comment to %s: %s", issue_key, e)
            result["errors"].append(f"Comment failed: {e}")

        # Apply automatic transition based on MR state
        try:
            transition_id = self._get_transition_id_for_state(issue_key, mr.state)
            if transition_id:
                self.jira.transition_issue(issue_key, transition_id)
                result["transition_applied"] = True
        except Exception as e:
            logger.error("Failed to transition %s: %s", issue_key, e)
            result["errors"].append(f"Transition failed: {e}")

        result["success"] = len(result["errors"]) == 0
        return result

    def handle_webhook(self, payload: dict[str, Any]) -> dict[str, Any]:
        """
        Handle GitLab webhook payload.

        Args:
            payload: Webhook payload from GitLab.

        Returns:
            Processing result.
        """
        object_kind = payload.get("object_kind")

        if object_kind != "merge_request":
            logger.info("Ignoring webhook: %s", object_kind)
            return {"success": False, "errors": ["Not a merge_request webhook"]}

        # Parse MR data
        mr_data = payload.get("object_attributes", {})
        event_action = mr_data.get("action")

        # Map event action to MR state
        state_map = {
            "open": MRState.OPENED,
            "update": MRState.OPENED,
            "approve": MRState.APPROVED,
            "approved": MRState.APPROVED,
            "merge": MRState.MERGED,
            "merged": MRState.MERGED,
            "close": MRState.CLOSED,
            "closed": MRState.CLOSED,
        }
        mr_state = state_map.get(event_action, MRState.OPENED)

        mr = MergeRequest(
            iid=mr_data.get("iid"),
            project_id=payload.get("project", {}).get("id"),
            source_branch=mr_data.get("source_branch"),
            target_branch=mr_data.get("target_branch"),
            title=mr_data.get("title"),
            description=mr_data.get("description"),
            state=mr_state,
            web_url=mr_data.get("url"),
            author=payload.get("user", {}),
        )

        # Parse commits if available
        commits_data = payload.get("commits", [])
        commits = [
            Commit(
                id=c.get("id"),
                message=c.get("message"),
                author_name=c.get("author", {}).get("name"),
                author_email=c.get("author", {}).get("email"),
                timestamp=c.get("timestamp"),
            )
            for c in commits_data
        ]

        return self.process_mr(mr, commits)
